package com.yellowpepper.transferservice.execptions;

/**
 * Exception for the errors generated by the Exchange Service.
 */
public class ExchangeServiceException extends Throwable {
    private static final String MESSAGE_EXCEPTION = "exchange-currency-error";

    public ExchangeServiceException() {
        super(MESSAGE_EXCEPTION);
    }
}
